[package]
name = "wamp"
version = "0.1.0"
authors = ["Daniel Yule <yule@cs.dal.ca>"]
build = "build.rs"

[lib]
name = "wamp"
path = "src/lib.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "*", optional = true }
syntex = "*"

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = { version = "*", optional = true }
websocket = "0.15.1"
url = "*"
log = "0.3"
env_logger = "0.3"
rmp = {version = "0.7"}
rmp-serde = {version = "0.9"}
ws = "0.4"
rand = "0.3"
eventual = "0.1.7"
